source "https://rubygems.org"

gem "ellen-alias"
gem "ellen-cron"
gem "ellen-github"
gem "ellen-google_image"
gem "ellen-nurupo", git: "https://gist.github.com/0146d99b96f938898d08.git", require: "nurupo"
gem "ellen-redis"
gem "ellen-slack"
gem "ellen-syoboi_calendar"
gem "pry"
gem "rake"
