source "https://rubygems.org"

gem "pry"
gem "rake"
gem "ruboty", github: "r7kamura/ruboty"
gem "ruboty-alias", github: "r7kamura/ruboty-alias"
gem "ruboty-cron"
gem "ruboty-github"
gem "ruboty-google_image"
gem "ruboty-lgtm"
gem "ruboty-redis"
gem "ruboty-slack"
gem "ruboty-syoboi_calendar"
gem "ruboty-talk"
