source "https://rubygems.org"

gem "pry"
gem "rake"
gem "ruboty", github: "r7kamura/ruboty"
gem "ruboty-alias"
gem "ruboty-cron"
gem "ruboty-github"
gem "ruboty-google_image"
gem "ruboty-lgtm"
gem "ruboty-redis"
gem "ruboty-slack"
gem "ruboty-syoboi_calendar"
gem "ruboty-talk"
gem "ruboty-kokodeikku", git: "https://gist.github.com/r7kamura/529cab313a3bf792fcf9"
gem "ikku", github: "r7kamura/ikku"
